# Usa una imagen base de Node.js con la versión que necesitas.
FROM node:18.13.0

# Establece el directorio de trabajo en el contenedor.
WORKDIR /app

# Copia todos los archivos del proyecto al contenedor.
COPY . /app

# Instala las dependencias del proyecto.
RUN npm install

EXPOSE 3000

# Especifica el comando de inicio de la aplicación.
CMD ["node", "server.js"]
